add_executable(module_operators test_operators.cu)
target_link_libraries(module_operators PRIVATE phix)
set_target_properties(module_operators PROPERTIES CUDA_SEPARABLE_COMPILATION ON)
add_test(NAME module_operators COMMAND module_operators)

add_executable(module_face_ops test_face_ops.cu)
target_link_libraries(module_face_ops PRIVATE phix)
set_target_properties(module_face_ops PROPERTIES CUDA_SEPARABLE_COMPILATION ON)
add_test(NAME module_face_ops COMMAND module_face_ops)

add_executable(module_face_pw test_face_pw.cu)
target_link_libraries(module_face_pw PRIVATE phix)
set_target_properties(module_face_pw PROPERTIES CUDA_SEPARABLE_COMPILATION ON)
add_test(NAME module_face_pw COMMAND module_face_pw)

add_executable(module_schemes_ext test_schemes_ext.cu)
target_link_libraries(module_schemes_ext PRIVATE phix)
set_target_properties(module_schemes_ext PROPERTIES CUDA_SEPARABLE_COMPILATION ON)
add_test(NAME module_schemes_ext COMMAND module_schemes_ext)

add_executable(module_anisotropy test_anisotropy.cu)
target_link_libraries(module_anisotropy PRIVATE phix)
set_target_properties(module_anisotropy PROPERTIES CUDA_SEPARABLE_COMPILATION ON)
add_test(NAME module_anisotropy COMMAND module_anisotropy)
