add_executable(module_operators test_operators.cu)
target_link_libraries(module_operators PRIVATE phix)
set_target_properties(module_operators PROPERTIES CUDA_SEPARABLE_COMPILATION ON)
add_test(NAME module_operators COMMAND module_operators)

add_executable(module_face_ops test_face_ops.cu)
target_link_libraries(module_face_ops PRIVATE phix)
set_target_properties(module_face_ops PROPERTIES CUDA_SEPARABLE_COMPILATION ON)
add_test(NAME module_face_ops COMMAND module_face_ops)
